# Generated by Django 5.0.6 on 2024-10-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_cart_cartitem_product_delete_user_cartitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(default='path/to/default/image.jpg', upload_to='products/'),
        ),
    ]
