# Generated by Django 5.0.6 on 2024-11-19 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_product_genre_alter_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='genre',
            field=models.CharField(choices=[('clothing', 'Clothing'), ('personal_accessories', 'Personal Accessories'), ('ornamentation', 'Ornamentation'), ('gadgets', 'Gadgets'), ('beauty_personal_care', 'Beauty & Personal Care'), ('pet_accessories', 'Pet Accessories'), ('tour_trips', 'Tour & Trips'), ('women_clothing', 'Women Clothing')], default='clothing', max_length=50),
        ),
    ]
